# Generated by Django 4.2 on 2023-08-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampletype',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Priority'),
        ),
        migrations.AlterUniqueTogether(
            name='sampletype',
            unique_together={('short_name', 'priority')},
        ),
    ]
