# Generated by Django 4.2 on 2024-02-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('core', '0002_rename_date_time_bottle_closed'), ('core', '0003_alter_instrument_unique_together_and_more'), ('core', '0004_rename_last_modified_date_sample_last_modified')]

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottle',
            old_name='date_time',
            new_name='closed',
        ),
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='variablename',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='station',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='variablename',
            name='mission',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='last_modified_date',
            new_name='last_modified',
        ),
    ]
