# Generated by Django 4.2 on 2023-08-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampletype',
            old_name='name',
            new_name='long_name',
        ),
        migrations.RemoveField(
            model_name='sampletype',
            name='units',
        ),
        migrations.AddField(
            model_name='sample',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Sample Comments'),
        ),
        migrations.CreateModel(
            name='SampleFileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_config_name', models.CharField(blank=True, help_text='Human readable name of this configuration to assist in choosing the configuration. If autogenerated this will be the file type and sample typeshort name (i.e csv - oxy for oxygen loaded from a csv file', max_length=50, null=True, verbose_name='Configuration Name')),
                ('file_type', models.CharField(help_text='file type extension e.g csv, xls, xlsx, dat', max_length=5, verbose_name='File Type')),
                ('header', models.IntegerField(default=0, help_text='The row containing headers is often not the first row of a file. This value indicates what row it is normally located on.', verbose_name='Header Row')),
                ('sample_field', models.CharField(help_text='Lowercase name of the column that contains the bottle ids', max_length=50, verbose_name='Sample Column')),
                ('value_field', models.CharField(help_text='Lowercase name of the column that contains the value data', max_length=50, verbose_name='Value Column')),
                ('tab', models.CharField(blank=True, help_text='the tab name data is located on', max_length=20, null=True, verbose_name='Tab Name')),
                ('flag_field', models.CharField(blank=True, help_text='Lowercase name of the column that contains flags, if it exists', max_length=50, null=True, verbose_name='Flag Column')),
                ('replicate_field', models.CharField(blank=True, help_text='Lowercase name of the column indicating a replicate, if it exists', max_length=50, null=True, verbose_name='Replicate Column')),
                ('comment_field', models.CharField(blank=True, help_text='Lowercase name of the column containing comments, if it exists', max_length=50, null=True, verbose_name='Comment Column')),
                ('sample_type', models.ForeignKey(help_text='The sample type this configuration describes', on_delete=django.db.models.deletion.CASCADE, related_name='sample_file_configs', to='core.sampletype', verbose_name='Sample Type')),
            ],
        ),
    ]
