# Generated by Django 4.2 on 2023-08-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampletype',
            options={'ordering': ('is_sensor', 'short_name')},
        ),
        migrations.AlterField(
            model_name='missionsampleconfig',
            name='mission',
            field=models.ForeignKey(help_text='Mission a sample type was loaded for', on_delete=django.db.models.deletion.CASCADE, related_name='mission_sample_configs', to='core.mission', verbose_name='Mission'),
        ),
    ]
