# Generated by Django 4.2 on 2024-02-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileconfigurationmapping',
            name='config',
        ),
        migrations.DeleteModel(
            name='ElogConfig',
        ),
        migrations.DeleteModel(
            name='FileConfiguration',
        ),
        migrations.DeleteModel(
            name='FileConfigurationMapping',
        ),
    ]
