# Generated by Django 4.2 on 2024-01-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_DO_NOT_SQUASH_OR_DELETE_create_global_sample_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstrumentSensor',
            new_name='Attachment',
        ),
        migrations.RenameField(
            model_name='discretesamplevalue',
            old_name='sample_datatype',
            new_name='datatype',
        ),
        migrations.RemoveField(
            model_name='sampletypeconfig',
            name='replicate_field',
        ),
        migrations.AddField(
            model_name='instrument',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='core.mission', verbose_name='Mission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.mission', verbose_name='Mission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variablename',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='core.mission', verbose_name='Mission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biochemupload',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.missionsampletype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.missionsampletype', verbose_name='Type'),
        ),
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together={('mission', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('mission', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='variablename',
            unique_together={('mission', 'name')},
        ),
    ]
