# Generated by Django 4.2 on 2023-09-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sampletype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='bio_upload_date',
            field=models.DateTimeField(blank=True, help_text='Date of last BioChem upload', null=True, verbose_name='BioChem Uploaded'),
        ),
        migrations.AddField(
            model_name='sample',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, help_text='Date sample was last updated', verbose_name='Sample Modified'),
        ),
    ]
