# Generated by Django 4.2 on 2024-05-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_action_latitude_alter_action_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='discretesamplevalue',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True, verbose_name='Detection Limit'),
        ),
    ]
