# Generated by Django 4.2 on 2023-12-21 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_DO_NOT_SQUASH_OR_DELETE_create_global_sample_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampletypeconfig',
            name='replicate_field',
        ),
        migrations.AlterField(
            model_name='biochemupload',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.missionsampletype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.missionsampletype', verbose_name='Type'),
        ),
    ]
