# Generated by Django 4.2 on 2023-08-02 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_error_type_alter_fileerror_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing ID'), (2, 'Missing Value'), (3, 'Validation Error')], default=0, verbose_name='Error type'),
        ),
        migrations.AlterField(
            model_name='fileerror',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing ID'), (2, 'Missing Value'), (3, 'Validation Error')], default=0, verbose_name='Error type'),
        ),
        migrations.CreateModel(
            name='ValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing ID'), (2, 'Missing Value'), (3, 'Validation Error')], default=0, verbose_name='Error type')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_errors', to='core.event', verbose_name='Event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
