# Generated by Django 4.2 on 2023-08-13 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_sampletype_long_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discretesamplevalue',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrete_value', to='core.sample', verbose_name='Sample'),
        ),
    ]
