# Generated by Django 4.2 on 2023-07-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_instrument_event_station_datafiledirectory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_sample_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='End Sample ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='sample_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sample ID'),
        ),
    ]
