# Generated by Django 4.2 on 2023-08-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sampletype_unique_together_sampletypeconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionSampleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.ForeignKey(help_text='Sample configuration used in a mission', on_delete=django.db.models.deletion.DO_NOTHING, related_name='mission_sample_configs', to='core.sampletypeconfig', verbose_name='Sample Configuration')),
                ('mission', models.ForeignKey(help_text='Mission a sample type was loaded for', on_delete=django.db.models.deletion.CASCADE, related_name='mission_sample_types', to='core.mission', verbose_name='Mission')),
            ],
        ),
        migrations.DeleteModel(
            name='MissionSampleType',
        ),
    ]
