# Generated by Django 4.2 on 2023-12-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sampletypeconfig_replicate_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discretesamplevalue',
            old_name='sample_datatype',
            new_name='datatype',
        ),
    ]
