# Generated by Django 4.2 on 2023-08-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_error_type_alter_fileerror_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('date_time',)},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ('type', 'name')},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ('name',)},
        ),
    ]
