# Generated by Django 4.2 on 2023-09-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sample_bio_upload_date_sample_last_modified_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileconfigurationmapping',
            options={'ordering': ('field',)},
        ),
        migrations.AddField(
            model_name='fileconfigurationmapping',
            name='purpose',
            field=models.CharField(blank=True, help_text='Describe the variable', max_length=127, null=True, verbose_name='Purpose'),
        ),
    ]
