# Generated by Django 4.2 on 2023-08-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_discretesamplevalue_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='comment',
        ),
        migrations.AddField(
            model_name='discretesamplevalue',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Sample Comments'),
        ),
        migrations.CreateModel(
            name='BioChemUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(blank=True, help_text='The last time this sensor/sample was uploaded to biochem', null=True, verbose_name='Upload Date')),
                ('modified_date', models.DateTimeField(blank=True, help_text='The last time this sensor/sample was modified', null=True, verbose_name='Upload Date')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.mission', verbose_name='Mission')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.sampletype', verbose_name='Type')),
            ],
        ),
    ]
