# Generated by Django 4.2 on 2024-01-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_instrumentsensor_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionsampleconfig',
            name='config',
        ),
        migrations.RemoveField(
            model_name='missionsampleconfig',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='sampletypeconfig',
            name='sample_type',
        ),
        migrations.DeleteModel(
            name='GlobalSampleType',
        ),
        migrations.DeleteModel(
            name='MissionSampleConfig',
        ),
        migrations.DeleteModel(
            name='SampleTypeConfig',
        ),
    ]
