# Generated by Django 4.2 on 2024-02-14 15:19

from django.db import migrations, models, transaction


def copy_geographic_region(apps, schema_editor):
    database = schema_editor.atomic.using
    Mission = apps.get_model('core', 'Mission')
    GeographicRegion = apps.get_model('core', 'GeographicRegion')

    mission = Mission.objects.using(database).first()
    if hasattr(mission, 'geographic_region') and mission.geographic_region:
        with transaction.atomic():
            region = GeographicRegion.objects.using(database).get(pk=mission.geographic_region)
            mission.geographic_region = region.name
            Mission.objects.using(database).bulk_update([mission], ['geographic_region'])


def reverse_copy_geographic_region(apps, schema_editor):
    database = schema_editor.atomic.using
    Mission = apps.get_model('core', 'Mission')
    GeographicRegion = apps.get_model('core', 'GeographicRegion')

    mission = Mission.objects.using(database).first()
    if hasattr(mission, 'geographic_region') and  mission.geographic_region:
        with transaction.atomic():
            region = GeographicRegion.objects.using(database).get_or_create(name=mission.geographic_region)[0]
            mission.geographic_region = region.pk
            Mission.objects.using(database).bulk_update([mission], ['geographic_region'])



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_date_time_bottle_closed_squashed_0004_rename_last_modified_date_sample_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileconfigurationmapping',
            name='config',
        ),
        migrations.DeleteModel(
            name='ElogConfig',
        ),
        migrations.DeleteModel(
            name='FileConfiguration',
        ),
        migrations.DeleteModel(
            name='FileConfigurationMapping',
        ),
        migrations.AlterField(
            model_name='mission',
            name='geographic_region',
            field=models.CharField(help_text='Terms describing the geographic region where the mission took place', max_length=100, verbose_name='Geographic Region'),
        ),
        migrations.RunPython(copy_geographic_region, reverse_copy_geographic_region),
        migrations.DeleteModel(
            name='GeographicRegion',
        ),
    ]
