# Generated by Django 4.2 on 2024-01-02 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_sample_datatype_discretesamplevalue_datatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='core.mission', verbose_name='Mission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.mission', verbose_name='Mission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variablename',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='core.mission', verbose_name='Mission'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together={('mission', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('mission', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='variablename',
            unique_together={('mission', 'name')},
        ),
    ]
