# Generated by Django 4.2 on 2023-08-08 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_action_options_alter_instrument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_sample_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='End Bottle'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sample_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start Bottle'),
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Fired Date/Time')),
                ('bottle_id', models.IntegerField(verbose_name='Bottle ID')),
                ('bottle_number', models.IntegerField(blank=True, null=True, verbose_name='Bottle Number')),
                ('pressure', models.FloatField(default=0.0, verbose_name='Pressure')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottles', to='core.event', verbose_name='Event')),
            ],
            options={
                'ordering': ['bottle_id'],
                'unique_together': {('event', 'bottle_number')},
            },
        ),
    ]
