# Generated by Django 4.2 on 2023-10-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_fileconfigurationmapping_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcDatabaseConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.IntegerField(choices=[(1, 'Oracle')], verbose_name='Database Type')),
                ('host', models.CharField(max_length=50, verbose_name='Database Server Address')),
                ('name', models.CharField(help_text='TTRAN/PTRAN', max_length=20, verbose_name='Database Name')),
                ('port', models.IntegerField(default=1521, verbose_name='Port')),
                ('account_name', models.CharField(max_length=20, verbose_name='User Name')),
            ],
        ),
        migrations.AlterField(
            model_name='error',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing ID'), (2, 'Missing Value'), (3, 'Validation Error'), (4, 'Bottle Error')], default=0, verbose_name='Error type'),
        ),
        migrations.AlterField(
            model_name='fileerror',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing ID'), (2, 'Missing Value'), (3, 'Validation Error'), (4, 'Bottle Error')], default=0, verbose_name='Error type'),
        ),
        migrations.AlterField(
            model_name='validationerror',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing ID'), (2, 'Missing Value'), (3, 'Validation Error'), (4, 'Bottle Error')], default=0, verbose_name='Error type'),
        ),
    ]
