# Generated by Django 4.2 on 2024-01-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_instrument_mission_station_mission_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstrumentSensor',
            new_name='Attachments',
        ),
    ]
