# Generated by Django 4.2 on 2023-08-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_action_sounding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataFileDirectory',
        ),
    ]
