# Generated by Django 4.2 on 2024-06-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_error_code_fileerror_code_validationerror_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='biochemupload',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'upload'), (2, 'uploaded'), (3, 'delete')], null=True, verbose_name='Status'),
        ),
    ]
