# Generated by Django 4.2 on 2023-07-31 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_station_alter_event_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('type', models.IntegerField(choices=[(0, 'Unknown')], default=0, verbose_name='Error type')),
                ('file_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='File Name')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='core.mission', verbose_name='Mission')),
            ],
        ),
    ]
