# Generated by Django 4.2 on 2023-10-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bcdatabaseconnections_alter_error_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcdatabaseconnections',
            name='engine',
            field=models.IntegerField(choices=[(1, 'Oracle')], default=1, verbose_name='Database Type'),
        ),
    ]
