# Generated by Django 4.2 on 2024-02-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_fileconfigurationmapping_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='wire_angle',
            field=models.FloatField(blank=True, null=True, verbose_name='Wire Angle'),
        ),
    ]
