# Generated by Django 4.2 on 2024-02-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_missionsampleconfig_config_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BcDatabaseConnection',
        ),
    ]
