# Generated by Django 4.2 on 2023-08-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_datafiledirectory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='sounding',
            field=models.FloatField(blank=True, null=True, verbose_name='Sounding'),
        ),
    ]
