# Generated by Django 4.2 on 2023-10-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bcdatabaseconnections_engine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BcDatabaseConnections',
            new_name='BcDatabaseConnection',
        ),
    ]
