# Generated by Django 4.2 on 2023-08-09 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_tables', '0001_initial'),
        ('core', '0006_sample_samplevalue_sampletype_sample_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscreteSampleValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replicate', models.IntegerField(default=1, help_text='Replicates occur when there are multiple samples of the same type form the same bottle.', verbose_name='Replicate #')),
                ('value', models.FloatField(verbose_name='Value')),
                ('flag', models.IntegerField(blank=True, null=True, verbose_name='Data Quality Flag')),
            ],
        ),
        migrations.AlterField(
            model_name='sample',
            name='bottle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.bottle', verbose_name='Bottle'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.sampletype', verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='SampleValue',
        ),
        migrations.AddField(
            model_name='discretesamplevalue',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrete_values', to='core.sample', verbose_name='Sample'),
        ),
        migrations.AddField(
            model_name='discretesamplevalue',
            name='sample_datatype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bio_tables.bcdatatype', verbose_name='BioChem DataType'),
        ),
    ]
