# Generated by Django 4.2 on 2023-07-31 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=18, verbose_name='File Type')),
            ],
        ),
        migrations.CreateModel(
            name='FileConfigurationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='Required Field')),
                ('mapped_to', models.CharField(max_length=100, verbose_name='Existing Field')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.fileconfiguration', verbose_name='Configuration File')),
            ],
        ),
        migrations.CreateModel(
            name='ElogConfig',
            fields=[
                ('fileconfiguration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.fileconfiguration')),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elogconfig', to='core.mission', verbose_name='Mission')),
            ],
            bases=('core.fileconfiguration',),
        ),
    ]
