# Generated by Django 4.2 on 2024-02-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_wire_angle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing ID'), (2, 'Missing Value'), (3, 'Validation Error'), (4, 'Bottle Error'), (5, 'Biochem Error'), (6, 'Event Error'), (7, 'Sample Error'), (8, 'Plankton Error')], default=0, verbose_name='Error type'),
        ),
        migrations.AlterField(
            model_name='fileerror',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing ID'), (2, 'Missing Value'), (3, 'Validation Error'), (4, 'Bottle Error'), (5, 'Biochem Error'), (6, 'Event Error'), (7, 'Sample Error'), (8, 'Plankton Error')], default=0, verbose_name='Error type'),
        ),
        migrations.AlterField(
            model_name='validationerror',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing ID'), (2, 'Missing Value'), (3, 'Validation Error'), (4, 'Bottle Error'), (5, 'Biochem Error'), (6, 'Event Error'), (7, 'Sample Error'), (8, 'Plankton Error')], default=0, verbose_name='Error type'),
        ),
    ]
