# Generated by Django 4.2 on 2023-08-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fileconfiguration_fileconfigurationmapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileconfigurationmapping',
            name='required',
            field=models.BooleanField(default=False, help_text='Indicate if this is a required field for validation', verbose_name='Is Required'),
        ),
        migrations.AlterField(
            model_name='fileconfigurationmapping',
            name='field',
            field=models.CharField(help_text='The field DART is expecting', max_length=100, verbose_name='Dart Field'),
        ),
        migrations.AlterField(
            model_name='fileconfigurationmapping',
            name='mapped_to',
            field=models.CharField(help_text='The field Elog has', max_length=100, verbose_name='Elog Field'),
        ),
    ]
