# Generated by Django 4.2 on 2023-08-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_discretesamplevalue_alter_sample_bottle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampletype',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='sampletype',
            name='units',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Units of Measure'),
        ),
    ]
