# Generated by Django 4.2 on 2023-10-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_bcdatabaseconnections_bcdatabaseconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
