# Generated by Django 4.2 on 2023-10-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_tables', '0002_bcupdate'),
        ('core', '0008_bottle_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionSampleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_sample_types', to='bio_tables.bcdatatype', verbose_name='BioChem DataType')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_sample_types', to='core.mission', verbose_name='Mission')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_sample_types', to='core.sampletype', verbose_name='Sample Type')),
            ],
        ),
    ]
