# Generated by Django 4.2 on 2023-08-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fileconfigurationmapping_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing ID'), (2, 'Missing Field')], default=0, verbose_name='Error type'),
        ),
    ]
