# Generated by Django 4.2 on 2023-08-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_samplefilesettings_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplefilesettings',
            name='file_config_name',
        ),
        migrations.AlterField(
            model_name='samplefilesettings',
            name='tab',
            field=models.IntegerField(default=0, help_text='the tab number data is located on, for MS Excel files the first tab is zero', verbose_name='Tab'),
        ),
    ]
