# Generated by Django 4.2 on 2023-08-01 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_error_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='file_name',
        ),
        migrations.CreateModel(
            name='FileError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing ID'), (2, 'Missing Field')], default=0, verbose_name='Error type')),
                ('file_name', models.CharField(max_length=50, verbose_name='File Name')),
                ('line', models.IntegerField(blank=True, null=True, verbose_name='Line/Object')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_errors', to='core.mission', verbose_name='Mission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
