# Generated by Django 4.2 on 2023-08-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_samplefilesettings_file_config_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplefilesettings',
            name='allow_blank',
            field=models.BooleanField(default=True, help_text='Should values be kept if the sample column is blank?', verbose_name='Allow Blank Samples?'),
        ),
        migrations.AddField(
            model_name='samplefilesettings',
            name='allow_replicate',
            field=models.BooleanField(default=True, help_text='Can this sample have replicate sample values?', verbose_name='Allow Replicate Samples?'),
        ),
        migrations.AlterField(
            model_name='samplefilesettings',
            name='tab',
            field=models.IntegerField(default=0, help_text='The tab number data is located on.For MS Excel, the first tab is zero', verbose_name='Tab'),
        ),
    ]
