# Generated by Django 4.2 on 2023-08-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_samplefilesettings_allow_blank_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sampletype',
            unique_together={('short_name', 'priority')},
        ),
    ]
