# Generated by Django 4.2 on 2023-10-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_sample_bio_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing ID'), (2, 'Missing Value'), (3, 'Validation Error'), (4, 'Bottle Error'), (5, 'Biochem Error')], default=0, verbose_name='Error type'),
        ),
        migrations.AlterField(
            model_name='fileerror',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing ID'), (2, 'Missing Value'), (3, 'Validation Error'), (4, 'Bottle Error'), (5, 'Biochem Error')], default=0, verbose_name='Error type'),
        ),
        migrations.AlterField(
            model_name='validationerror',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing ID'), (2, 'Missing Value'), (3, 'Validation Error'), (4, 'Bottle Error'), (5, 'Biochem Error')], default=0, verbose_name='Error type'),
        ),
    ]
