# Generated by Django 4.2 on 2025-07-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_planktonsample_gear_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='end_underway_sample',
            field=models.IntegerField(blank=True, null=True, verbose_name='End Underway Sample ID'),
        ),
        migrations.AddField(
            model_name='mission',
            name='start_underway_sample',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start Underway Sample ID'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='mesh_size',
            field=models.IntegerField(blank=True, default=0, help_text='Mesh size of the net material in um', null=True, verbose_name='Mesh Size'),
        ),
    ]
