# Generated by Django 4.2 on 2023-10-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_error_type_alter_fileerror_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcdatabaseconnection',
            name='uploader',
            field=models.CharField(blank=True, help_text='If not Account Name', max_length=20, null=True, verbose_name='Uploader Name'),
        ),
        migrations.AddField(
            model_name='discretesamplevalue',
            name='dis_data_num',
            field=models.IntegerField(blank=True, help_text='The BCD unique ID provided once a sample has been uploaded', null=True, verbose_name='BioChem Data Number'),
        ),
        migrations.AlterField(
            model_name='bcdatabaseconnection',
            name='account_name',
            field=models.CharField(max_length=20, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='bcdatabaseconnection',
            name='host',
            field=models.CharField(max_length=50, verbose_name='Server Address'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='platform',
            field=models.CharField(default='N/A', help_text='May be vessel name, fishing boat, wharf, various small vessels, multiple ships. Check that name is spelled correctly. “Unknown” is acceptable for historical data', max_length=75, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='protocol',
            field=models.CharField(default='N/A', help_text='A citation should be given if standard protocols were used during the mission. The use of non-standard protocols should be noted and further details provided in the collector comments field', max_length=75, verbose_name='Protocol'),
        ),
    ]
