# Generated by Django 4.2 on 2023-08-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_instrument_type_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('event_id',)},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('event_id', 'mission')},
        ),
    ]
