# Generated by Django 4.2 on 2023-11-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bcdatabaseconnection_uploader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='platform',
            field=models.CharField(default='N/A', help_text='May be vessel name, fishing boat, wharf, various small vessels, multiple ships. Check that name is spelled correctly. “Unknown” is acceptable for historical data', max_length=50, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='protocol',
            field=models.CharField(default='N/A', help_text='A citation should be given if standard protocols were used during the mission. The use of non-standard protocols should be noted and further details provided in the collector comments field', max_length=50, verbose_name='Protocol'),
        ),
    ]
