# Generated by Django 4.2 on 2025-08-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_mission_end_underway_sample_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValidationError',
            new_name='EventError',
        ),
        migrations.RenameModel(
            old_name='Error',
            new_name='MissionError',
        ),
        migrations.AlterField(
            model_name='mission',
            name='start_underway_sample',
            field=models.IntegerField(blank=True, help_text='A starting and ending sample ID can be provided for a range of samples to exclude from the validation when loading samples. This is primarily for underway samples that will be present in a sample file, but have no associated events or bottles.', null=True, verbose_name='Start Underway Sample ID'),
        ),
    ]
