# Generated by Django 4.2 on 2023-08-01 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_instrumentsensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Field Name')),
            ],
            options={
                'ordering': (django.db.models.functions.text.Lower('name'),),
            },
        ),
        migrations.CreateModel(
            name='VariableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Field Value')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='core.action', verbose_name='Action')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='core.variablename', verbose_name='Field Name')),
            ],
        ),
    ]
