# Generated by Django 4.2 on 2023-11-06 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_tables', '0003_bclifehistory_bcsex'),
        ('core', '0013_alter_mission_platform_alter_mission_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanktonSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('split_fraction', models.FloatField(default=1, verbose_name='Split Fraction')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='count')),
                ('raw_wet_weight', models.FloatField(blank=True, null=True, verbose_name='Weight Weight')),
                ('raw_dry_weight', models.FloatField(blank=True, null=True, verbose_name='Dry Weight')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='Volume')),
                ('percent', models.FloatField(blank=True, null=True, verbose_name='Percent')),
                ('comments', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comments')),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plankton_data', to='core.bottle', verbose_name='Bottle')),
                ('gear_type', models.ForeignKey(default=90000002, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plankton_data', to='bio_tables.bcgear', verbose_name='Gear Type')),
                ('taxa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plankton_data', to='bio_tables.bcnatnltaxoncode', verbose_name='Taxonomy')),
            ],
        ),
    ]
