# Generated by Django 4.2 on 2023-11-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_tables', '0004_alter_bclifehistory_data_center_code_and_more'),
        ('core', '0014_planktonsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='planktonsample',
            name='max_sieve',
            field=models.FloatField(default=0.55, verbose_name='Max Sieve'),
        ),
        migrations.AddField(
            model_name='planktonsample',
            name='min_sieve',
            field=models.FloatField(default=0.002, verbose_name='Max Sieve'),
        ),
        migrations.AddField(
            model_name='planktonsample',
            name='sex',
            field=models.ForeignKey(default=90000000, on_delete=django.db.models.deletion.DO_NOTHING, to='bio_tables.bcsex', verbose_name='Sex'),
        ),
        migrations.AddField(
            model_name='planktonsample',
            name='stage',
            field=models.ForeignKey(default=90000000, on_delete=django.db.models.deletion.DO_NOTHING, to='bio_tables.bclifehistory', verbose_name='Stage of Life'),
        ),
    ]
