# Generated by Django 4.2 on 2025-08-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_eventerror_comment_fileerror_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='description',
            field=models.CharField(blank=True, default='', help_text='The mission description should be someting like "Fall AZMP", "Groundfish", "AZOMP", which will be used as a subtitle in the loading status report', max_length=100, verbose_name='Mission Description'),
        ),
    ]
