# Generated by Django 4.2 on 2023-11-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_planktonsample_max_sieve_planktonsample_min_sieve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planktonsample',
            name='max_sieve',
            field=models.FloatField(blank=True, default=0.55, null=True, verbose_name='Max Sieve'),
        ),
    ]
