# Generated by Django 4.2 on 2025-08-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mission_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Example: "Fall AZMP", "Groundfish", "AZOMP".Used as a subtitle in the loading status report', max_length=100, verbose_name='Mission Description'),
        ),
    ]
