# Generated by Django 4.2 on 2025-09-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_mission_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human readable name of a file that people will refer to such as a "Bottle File" or "Andes Report" or "QAT File"', max_length=30, verbose_name='File Type Name')),
                ('extension', models.CharField(help_text='The extension used for this file, excluding the dot "BTL", not ".BTL"', max_length=10, verbose_name='File Extension')),
                ('description', models.CharField(help_text='Short description of what this file type will contain.', max_length=100, verbose_name='File Description')),
            ],
        ),
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Just the name of the file, does not include the file path.', max_length=100, verbose_name='File Name')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.event', verbose_name='Event')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.filetype', verbose_name='File Type')),
            ],
        ),
    ]
