# Generated by Django 4.2 on 2023-11-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_planktonsample_max_sieve'),
    ]

    operations = [
        migrations.AddField(
            model_name='planktonsample',
            name='proc_code',
            field=models.IntegerField(default=9999, verbose_name='Procedure Code'),
        ),
    ]
