# Generated by Django 4.2 on 2025-10-02 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_tables', '0001_initial'),
        ('core', '0017_filetype_eventfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='gear_type',
            field=models.ForeignKey(default=90000171, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bottles', to='bio_tables.bcgear', verbose_name='Gear Type'),
        ),
    ]
