# Generated by Django 4.2 on 2023-11-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_planktonsample_proc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='flow_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Flow Meter Start'),
        ),
        migrations.AddField(
            model_name='event',
            name='flow_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Flow Meter Start'),
        ),
        migrations.AddField(
            model_name='event',
            name='wire_out',
            field=models.FloatField(blank=True, null=True, verbose_name='Wire Out'),
        ),
    ]
