# Generated by Django 4.2 on 2026-01-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_bottle_gear_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventerror',
            name='type',
            field=models.IntegerField(blank=True, choices=[(9, 'Biochem Plankton Error'), (8, 'Plankton Error'), (7, 'Sample Error'), (6, 'Event Error'), (5, 'Biochem Error'), (4, 'Bottle Error'), (3, 'Validation Error'), (2, 'Missing Value'), (1, 'Missing ID'), (0, 'Unknown')], default=0, null=True, verbose_name='Error type'),
        ),
        migrations.AlterField(
            model_name='fileerror',
            name='type',
            field=models.IntegerField(blank=True, choices=[(9, 'Biochem Plankton Error'), (8, 'Plankton Error'), (7, 'Sample Error'), (6, 'Event Error'), (5, 'Biochem Error'), (4, 'Bottle Error'), (3, 'Validation Error'), (2, 'Missing Value'), (1, 'Missing ID'), (0, 'Unknown')], default=0, null=True, verbose_name='Error type'),
        ),
        migrations.AlterField(
            model_name='missionerror',
            name='type',
            field=models.IntegerField(blank=True, choices=[(9, 'Biochem Plankton Error'), (8, 'Plankton Error'), (7, 'Sample Error'), (6, 'Event Error'), (5, 'Biochem Error'), (4, 'Bottle Error'), (3, 'Validation Error'), (2, 'Missing Value'), (1, 'Missing ID'), (0, 'Unknown')], default=0, null=True, verbose_name='Error type'),
        ),
    ]
