# Generated by Django 4.2 on 2023-11-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_event_flow_end_event_flow_start_event_wire_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='planktonsample',
            name='mesh_size',
            field=models.IntegerField(blank=True, help_text='Mesh size of the net material in um', null=True, verbose_name='Mesh Size'),
        ),
        migrations.AlterField(
            model_name='event',
            name='flow_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Flow Meter End'),
        ),
    ]
