# Generated by Django 4.2 on 2023-11-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_planktonsample_mesh_size_alter_event_flow_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='planktonsample',
            name='plank_data_num',
            field=models.IntegerField(blank=True, help_text='key linking this plankton sample to a biochem staging table', null=True, verbose_name='Plankton data number'),
        ),
    ]
