# Generated by Django 5.2.9 on 2026-01-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_eventerror_type_alter_fileerror_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='fixed_station',
            field=models.BooleanField(default=False, help_text='If this is a fixed station, CTD events are loaded form BTL files.If not a fixed station, events must be loaded from CSV, ANDES or Elog before BTL files are loaded.', verbose_name='Is Fixed Station?'),
        ),
    ]
