# Generated by Django 5.2.11 on 2026-03-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_mission_fixed_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='biochem_discreate_mission_seq',
            field=models.IntegerField(blank=True, help_text="The mission sequence number of an existing Biochem discrete mission that this mission's discrete data should replace", null=True, verbose_name='Discrete Mission Sequences'),
        ),
        migrations.AddField(
            model_name='mission',
            name='biochem_plankton_mission_seq',
            field=models.IntegerField(blank=True, help_text="The mission sequence number of an existing Biochem Plankton mission that this mission's plankton data should replace", null=True, verbose_name='Plankton Mission Sequences'),
        ),
    ]
