# Generated by Django 4.2 on 2023-12-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_planktonsample_plank_data_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='pressure',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7, verbose_name='Pressure'),
        ),
    ]
