# Generated by Django 4.2 on 2023-12-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_bottle_latitude_alter_bottle_longitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionSampleType',
        ),
    ]
