# Generated by Django 5.2.11 on 2026-04-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_mission_biochem_discreate_mission_seq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='data_center',
            field=models.IntegerField(default=20, verbose_name='Data Center'),
        ),
    ]
