# Generated by Django 5.2.11 on 2026-04-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_mission_biochem_discreate_mission_seq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='gear_type',
            field=models.IntegerField(default=90000171, verbose_name='Gear Type'),
        ),
        migrations.AlterField(
            model_name='discretesamplevalue',
            name='datatype',
            field=models.IntegerField(blank=True, null=True, verbose_name='BioChem DataType'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='data_center',
            field=models.IntegerField(default=20, verbose_name='Data Center'),
        ),
        migrations.AlterField(
            model_name='planktonsample',
            name='sex',
            field=models.IntegerField(default=90000000, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='planktonsample',
            name='stage',
            field=models.IntegerField(default=90000000, verbose_name='Stage of Life'),
        ),
        migrations.AlterField(
            model_name='planktonsample',
            name='taxa',
            field=models.IntegerField(verbose_name='Taxonomy'),
        ),
    ]
