# Generated by Django 4.2 on 2023-12-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_bottle_latitude_alter_bottle_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biochemupload',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='The last time this sensor/sample was modified', null=True, verbose_name='Upload Date'),
        ),
    ]
