# Generated by Django 5.2.11 on 2026-04-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_bottle_gear_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionsampletype',
            name='datatype',
            field=models.IntegerField(blank=True, null=True, verbose_name='BioChem DataType'),
        ),
    ]
