# Generated by Django 5.2.11 on 2026-04-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_mission_data_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='gear_type',
            field=models.IntegerField(default=90000171, verbose_name='Gear Type'),
        ),
    ]
