# Generated by Django 5.2.11 on 2026-04-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_bottle_gear_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planktonsample',
            name='sex',
            field=models.IntegerField(default=90000000, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='planktonsample',
            name='stage',
            field=models.IntegerField(default=90000000, verbose_name='Stage of Life'),
        ),
        migrations.AlterField(
            model_name='planktonsample',
            name='taxa',
            field=models.IntegerField(verbose_name='Taxonomy'),
        ),
    ]
