# Generated by Django 5.2.14 on 2026-09-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_missionsampletype_datatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='collector_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Sample Comments'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='data_manager_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Sample Comments'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Event Comment'),
        ),
    ]
