# Generated by Django 4.2 on 2023-11-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biochem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bclifehistories',
            fields=[
                ('life_history_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('data_center_code', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('molt_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'BCLIFEHISTORIES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bcsexes',
            fields=[
                ('sex_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('data_center_code', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'BCSEXES',
                'managed': False,
            },
        ),
    ]
