# Generated by Django 4.2 on 2023-11-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biochem', '0002_bclifehistories_bcsexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bccollectionmethods',
            fields=[
                ('collection_method_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('data_center_code', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'BCCOLLECTIONMETHODS',
                'managed': False,
            },
        ),
    ]
