# Generated by Django 4.2 on 2023-11-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biochem', '0003_bccollectionmethods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bcprocedures',
            fields=[
                ('procedure_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('data_center_code', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'BCPROCEDURES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bcvolumemethods',
            fields=[
                ('volume_method_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('data_center_code', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'BCVOLUMEMETHODS',
                'managed': False,
            },
        ),
    ]
