# Generated by Django 4.2 on 2025-03-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biochem', '0005_bcdiscretehedrs_bcevents_bcmissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bcactivities',
            fields=[
                ('activity_seq', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_pointer_code', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'BCACTIVITIES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bcdiscretedtails',
            fields=[
                ('discrete_detail_seq', models.BigIntegerField(db_column='discrete_detail_seq', primary_key=True, serialize=False)),
                ('data_value', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('averaged_data', models.CharField(blank=True, max_length=1, null=True)),
                ('data_qc_code', models.CharField(blank=True, max_length=2, null=True)),
                ('detection_limit', models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True)),
                ('detail_collector', models.CharField(blank=True, max_length=50, null=True)),
                ('collector_sample_id', models.CharField(blank=True, max_length=50, null=True)),
                ('prod_created_date', models.DateField()),
                ('prod_created_by', models.CharField(blank=True, max_length=10, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'BCDISCRETEDTAILS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bclockedmissions',
            fields=[
                ('mission', models.OneToOneField(db_column='mission_seq', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='locked_missions', serialize=False, to='biochem.bcmissions')),
                ('mission_name', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptor', models.CharField(blank=True, max_length=50, null=True)),
                ('data_pointer_code', models.CharField(blank=True, max_length=2, null=True)),
                ('downloaded_by', models.CharField(blank=True, max_length=10, null=True)),
                ('downloaded_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BCLOCKEDMISSIONS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bcplanktnhedrs',
            fields=[
                ('plankton_seq', models.BigIntegerField(primary_key=True, serialize=False)),
                ('activity_seq', models.IntegerField()),
                ('gear_seq', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.IntegerField(blank=True, null=True)),
                ('end_time', models.IntegerField(blank=True, null=True)),
                ('phase_of_daylight', models.CharField(max_length=15)),
                ('start_lat', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('end_lat', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('start_lon', models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('end_lon', models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('time_qc_code', models.CharField(max_length=2)),
                ('position_qc_code', models.CharField(blank=True, max_length=2, null=True)),
                ('start_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('end_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sounding', models.IntegerField()),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('large_plankton_removed', models.CharField(blank=True, max_length=1, null=True)),
                ('mesh_size', models.IntegerField(blank=True, null=True)),
                ('collector_deployment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('collector_sample_id', models.CharField(max_length=50)),
                ('collector', models.CharField(blank=True, max_length=50, null=True)),
                ('collector_comment', models.CharField(blank=True, max_length=2000, null=True)),
                ('meters_sqd_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('data_manager_comment', models.CharField(blank=True, max_length=2000, null=True)),
                ('responsible_group', models.CharField(blank=True, max_length=50, null=True)),
                ('shared_data', models.CharField(blank=True, max_length=50, null=True)),
                ('prod_created_date', models.DateField()),
                ('prod_created_by', models.CharField(blank=True, max_length=10, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'BCPLANKTNHEDRS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bcplanktnindividls',
            fields=[
                ('plankton_individual_seq', models.BigIntegerField(db_column='pl_individual_seq', primary_key=True, serialize=False)),
                ('plankton_general_seq', models.BigIntegerField(blank=True, null=True)),
                ('bug_seq', models.IntegerField(blank=True, null=True)),
                ('data_value', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('data_qc_code', models.CharField(blank=True, max_length=2, null=True)),
                ('data_collector', models.CharField(blank=True, max_length=50, null=True)),
                ('prod_created_date', models.DateField()),
                ('prod_created_by', models.CharField(blank=True, max_length=10, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'BCPLANKTNINDIVIDLS',
                'managed': False,
            },
        ),
    ]
