# Generated by Django 4.2 on 2025-05-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biochem', '0006_bcactivities_bcdiscretedtails_bclockedmissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bccommenteditsdel',
            fields=[
                ('comment_seq', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'BCCOMMENTEDITSDEL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bcdiscretereplicteditsdel',
            fields=[
                ('discrete_replicate_seq', models.BigIntegerField(primary_key=True, serialize=False)),
                ('audit_delete', models.CharField(blank=True, default='T', max_length=1, null=True)),
            ],
            options={
                'db_table': 'BCDISCRETEREPLICTEDITSDEL',
                'managed': False,
            },
        ),
    ]
