# Generated by Django 4.2 on 2024-02-05 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCAnalysis',
            fields=[
                ('analysis_seq', models.IntegerField(primary_key=True, serialize=False, verbose_name='Analysis Code')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='BCDataCenter',
            fields=[
                ('data_center_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Data Center Code')),
                ('name', models.CharField(max_length=50, verbose_name='Data Center Name')),
                ('location', models.CharField(max_length=50, verbose_name='Data Center Location')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Data Center Description')),
            ],
        ),
        migrations.CreateModel(
            name='BCDataRetrieval',
            fields=[
                ('data_retrieval_seq', models.IntegerField(primary_key=True, serialize=False, verbose_name='Data Retrieval')),
                ('parameter_name', models.CharField(max_length=20, verbose_name='Parameter Name')),
                ('parameter_description', models.CharField(max_length=100, verbose_name='Parameter Description')),
                ('places_before', models.IntegerField(verbose_name='Places Before Decimal')),
                ('places_after', models.IntegerField(verbose_name='Places After Decimal')),
                ('minimum_value', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Maximum Value')),
                ('maximum_value', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Minimum Value')),
                ('originally_entered_by', models.CharField(max_length=30, verbose_name='Original Creator')),
                ('data_center_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_retrievals', to='bio_tables.bcdatacenter', verbose_name='Data Center')),
            ],
        ),
        migrations.CreateModel(
            name='BCUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(verbose_name='Last Updated')),
            ],
        ),
        migrations.CreateModel(
            name='BCVolumeMethod',
            fields=[
                ('volume_method_seq', models.IntegerField(help_text='Volume method code value.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Volume method name.', max_length=30)),
                ('description', models.CharField(blank=True, help_text='Volume method description.', max_length=1000, null=True)),
                ('data_center_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='volume_method_codes', to='bio_tables.bcdatacenter', verbose_name='Data Center')),
            ],
        ),
        migrations.CreateModel(
            name='BCUnit',
            fields=[
                ('unit_seq', models.IntegerField(primary_key=True, serialize=False, verbose_name='Unit Code')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('data_center_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='units', to='bio_tables.bcdatacenter', verbose_name='Data Center')),
            ],
        ),
        migrations.CreateModel(
            name='BCStorage',
            fields=[
                ('storage_seq', models.IntegerField(primary_key=True, serialize=False, verbose_name='Storage Method')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('data_center_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='storages', to='bio_tables.bcdatacenter', verbose_name='Data Center')),
            ],
        ),
        migrations.CreateModel(
            name='BCSex',
            fields=[
                ('sex_seq', models.IntegerField(help_text='Sex code.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the sex.', max_length=30)),
                ('description', models.CharField(blank=True, help_text='Sex description.', max_length=1000, null=True)),
                ('data_center_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sex_codes', to='bio_tables.bcdatacenter', verbose_name='Data Center')),
            ],
        ),
        migrations.CreateModel(
            name='BCSampleHandling',
            fields=[
                ('sample_handling_seq', models.IntegerField(primary_key=True, serialize=False, verbose_name='Sample Handling Method')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('data_center_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_handlings', to='bio_tables.bcdatacenter', verbose_name='Data Center')),
            ],
        ),
        migrations.CreateModel(
            name='BCProcedure',
            fields=[
                ('procedure_seq', models.IntegerField(help_text='Procedure code value.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Procedure name.', max_length=30)),
                ('description', models.CharField(blank=True, help_text='Procedure description.', max_length=1000, null=True)),
                ('data_center_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedure_codes', to='bio_tables.bcdatacenter', verbose_name='Data Center')),
            ],
        ),
        migrations.CreateModel(
            name='BCPreservation',
            fields=[
                ('preservation_seq', models.IntegerField(primary_key=True, serialize=False, verbose_name='Preservation Method')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Type')),
                ('data_center_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='preservations', to='bio_tables.bcdatacenter', verbose_name='Data Center')),
            ],
        ),
        migrations.CreateModel(
            name='BCNatnlTaxonCode',
            fields=[
                ('national_taxonomic_seq', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Data Center')),
                ('tsn', models.BigIntegerField(verbose_name='TSN ID')),
                ('taxonomic_name', models.CharField(max_length=100, verbose_name='Taxonomic Name')),
                ('best_nodc7', models.BigIntegerField(verbose_name='Best NODC7')),
                ('authority', models.CharField(blank=True, max_length=50, null=True, verbose_name='Authority')),
                ('collectors_comment', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Collector Comment')),
                ('data_managers_comment', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Data Manager Comment')),
                ('short_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Short Name')),
                ('tsn_itis', models.BigIntegerField(blank=True, null=True, verbose_name='TSN ITIS ID')),
                ('aphiaid', models.BigIntegerField(blank=True, null=True, verbose_name='APHIA ID')),
                ('data_center_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='taxon_codes', to='bio_tables.bcdatacenter', verbose_name='Data Center')),
            ],
        ),
        migrations.CreateModel(
            name='BCLifeHistory',
            fields=[
                ('life_history_seq', models.IntegerField(help_text='Development stage code (auto generated number).', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Development stage name.', max_length=30)),
                ('description', models.CharField(blank=True, help_text='Development stage description.', max_length=1000, null=True)),
                ('molt_number', models.CharField(blank=True, help_text='Accepted numeric standard to represent the molt stage.', max_length=20, null=True)),
                ('data_center_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='life_history_codes', to='bio_tables.bcdatacenter', verbose_name='Data Center')),
            ],
        ),
        migrations.CreateModel(
            name='BCGear',
            fields=[
                ('gear_seq', models.IntegerField(primary_key=True, serialize=False, verbose_name='Gear ID')),
                ('type', models.CharField(max_length=40, verbose_name='Type')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model')),
                ('gear_size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Size')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('data_center_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gear_codes', to='bio_tables.bcdatacenter', verbose_name='Data Center')),
            ],
        ),
        migrations.CreateModel(
            name='BCDataType',
            fields=[
                ('data_type_seq', models.IntegerField(primary_key=True, serialize=False, verbose_name='Data Type')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('conversion_equation', models.CharField(blank=True, max_length=250, null=True, verbose_name='Conversion Equation')),
                ('originally_entered_by', models.CharField(max_length=30, verbose_name='Original Creator')),
                ('method', models.CharField(max_length=20, verbose_name='Method')),
                ('priority', models.IntegerField(verbose_name='Priority')),
                ('p_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='P Code')),
                ('bodc_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='BODC Code')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_types', to='bio_tables.bcanalysis', verbose_name='Analysis')),
                ('data_center_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_types', to='bio_tables.bcdatacenter', verbose_name='Data Center')),
                ('data_retrieval', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_types', to='bio_tables.bcdataretrieval', verbose_name='Data Retrieval')),
                ('preservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_types', to='bio_tables.bcpreservation', verbose_name='Preservation')),
                ('sample_handling', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_types', to='bio_tables.bcsamplehandling', verbose_name='Sample Handling')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_types', to='bio_tables.bcstorage', verbose_name='Storage')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_types', to='bio_tables.bcunit', verbose_name='Unit')),
            ],
        ),
        migrations.AddField(
            model_name='bcdataretrieval',
            name='unit_seq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_retrievals', to='bio_tables.bcunit', verbose_name='Units'),
        ),
        migrations.CreateModel(
            name='BCCollectionMethod',
            fields=[
                ('collection_method_seq', models.IntegerField(help_text='Auto generated sequence number.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Common name of the collection method.', max_length=30)),
                ('description', models.CharField(blank=True, help_text='Description of the collection method code.', max_length=1000, null=True)),
                ('data_center_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collection_method_codes', to='bio_tables.bcdatacenter', verbose_name='Data Center')),
            ],
        ),
        migrations.AddField(
            model_name='bcanalysis',
            name='data_center_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_analyses', to='bio_tables.bcdatacenter', verbose_name='Data Center'),
        ),
    ]
