# Generated by Django 4.2 on 2023-08-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(verbose_name='Last Updated')),
            ],
        ),
    ]
