# Generated by Django 4.2 on 2023-11-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_tables', '0002_bcupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCLifeHistory',
            fields=[
                ('life_history_seq', models.IntegerField(help_text='Development stage code (auto generated number).', primary_key=True, serialize=False)),
                ('data_center_code', models.IntegerField(help_text='Assigned code value to represent a data center that holds data from which data may be obtained.')),
                ('name', models.CharField(help_text='Development stage name.', max_length=30)),
                ('description', models.CharField(blank=True, help_text='Development stage description.', max_length=1000, null=True)),
                ('molt_number', models.CharField(blank=True, help_text='Accepted numeric standard to represent the molt stage.', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BCSex',
            fields=[
                ('sex_seq', models.IntegerField(help_text='Sex code.', primary_key=True, serialize=False)),
                ('data_center_code', models.IntegerField(help_text='Assigned code value to represent a data center that holds data from which data may be obtained.')),
                ('name', models.CharField(help_text='Name of the sex.', max_length=30)),
                ('description', models.CharField(blank=True, help_text='Sex description.', max_length=1000, null=True)),
            ],
        ),
    ]
