# Generated by Django 4.2 on 2023-11-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio_tables', '0003_bclifehistory_bcsex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bclifehistory',
            name='data_center_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='life_history_codes', to='bio_tables.bcdatacenter', verbose_name='Data Center'),
        ),
        migrations.AlterField(
            model_name='bcsex',
            name='data_center_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sex_codes', to='bio_tables.bcdatacenter', verbose_name='Data Center'),
        ),
    ]
