# Generated by Django 4.2 on 2024-03-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='action',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
