# Generated by Django 4.2 on 2024-05-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0003_discretesamplevalue_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='dart_version',
            field=models.CharField(default='b7f674184f401a6a0192ba5e91462fcd3d97ee04', max_length=50, verbose_name='Dart Version'),
        ),
    ]
