# Generated by Django 4.2 on 2024-06-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0006_biochemupload_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='biochem_table',
        ),
        migrations.AlterField(
            model_name='biochemupload',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='The last time this sensor/sample was loaded', null=True, verbose_name='Modified Date'),
        ),
    ]
