# Generated by Django 4.2 on 2025-03-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0008_planktonsample_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='end_pressure',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='End Pressure'),
        ),
        migrations.AddField(
            model_name='planktonsample',
            name='flag',
            field=models.IntegerField(default=0, verbose_name='Data Quality Flag'),
        ),
        migrations.AlterField(
            model_name='error',
            name='type',
            field=models.IntegerField(choices=[(9, 'Biochem Plankton Error'), (8, 'Plankton Error'), (7, 'Sample Error'), (6, 'Event Error'), (5, 'Biochem Error'), (4, 'Bottle Error'), (3, 'Validation Error'), (2, 'Missing Value'), (1, 'Missing ID'), (0, 'Unknown')], default=0, verbose_name='Error type'),
        ),
        migrations.AlterField(
            model_name='fileerror',
            name='type',
            field=models.IntegerField(choices=[(9, 'Biochem Plankton Error'), (8, 'Plankton Error'), (7, 'Sample Error'), (6, 'Event Error'), (5, 'Biochem Error'), (4, 'Bottle Error'), (3, 'Validation Error'), (2, 'Missing Value'), (1, 'Missing ID'), (0, 'Unknown')], default=0, verbose_name='Error type'),
        ),
        migrations.AlterField(
            model_name='validationerror',
            name='type',
            field=models.IntegerField(choices=[(9, 'Biochem Plankton Error'), (8, 'Plankton Error'), (7, 'Sample Error'), (6, 'Event Error'), (5, 'Biochem Error'), (4, 'Bottle Error'), (3, 'Validation Error'), (2, 'Missing Value'), (1, 'Missing ID'), (0, 'Unknown')], default=0, verbose_name='Error type'),
        ),
    ]
