# Generated by Django 4.2 on 2025-05-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0009_bottle_end_pressure_planktonsample_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume'),
        ),
        migrations.AddField(
            model_name='event',
            name='flowmeter_constant',
            field=models.FloatField(blank=True, null=True, verbose_name='Flow Meter Constant'),
        ),
        migrations.AddField(
            model_name='event',
            name='surface_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Area (m²)'),
        ),
    ]
