# Generated by Django 4.2.23 on 2025-06-19 20:47

from django.db import migrations, models
import django.db.models.deletion

def migrate_all_models(apps, schema_editor):
    core_models = apps.get_app_config('core').get_models()
    dart_models = apps.get_app_config('dart').get_models()

    core_model_map = {model.__name__: model for model in core_models}
    dart_model_map = {model.__name__: model for model in dart_models}

    for model_name, core_model in core_model_map.items():
        if model_name in dart_model_map:
            dart_model = dart_model_map[model_name]
            for old_instance in core_model.objects.all():
                new_instance = dart_model()
                for field in core_model._meta.fields:
                    if hasattr(dart_model, field.name):
                        setattr(new_instance, field.name, getattr(old_instance, field.name))
                new_instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0011_remove_planktonsample_gear_type_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_all_models),
        migrations.AlterField(
            model_name='action',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='dart.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dart.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='biochemupload',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='dart.missionsampletype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottles', to='dart.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='mesh_size',
            field=models.IntegerField(blank=True, default=0, help_text='Mesh size of the net material in um', null=True, verbose_name='Mesh Size'),
        ),
        migrations.AlterField(
            model_name='discretesamplevalue',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrete_values', to='dart.sample', verbose_name='Sample'),
        ),
        migrations.AlterField(
            model_name='error',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='dart.mission', verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='event',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='dart.instrument', verbose_name='Instrument'),
        ),
        migrations.AlterField(
            model_name='event',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dart.mission', verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='event',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='dart.station', verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='fileerror',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_errors', to='dart.mission', verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='missionsampletype',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_sample_types', to='dart.mission', verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='planktonsample',
            name='bottle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plankton_data', to='dart.bottle', verbose_name='Bottle'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='bottle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='dart.bottle', verbose_name='Bottle'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='dart.missionsampletype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='validationerror',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_errors', to='dart.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='variablefield',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='dart.action', verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='variablefield',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='dart.variablename', verbose_name='Field Name'),
        ),
    ]
