# Generated by Django 4.2.23 on 2025-06-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0012_alter_action_event_alter_attachment_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='gear_type',
            field=models.IntegerField(default=90000002, verbose_name='Gear Type'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='mesh_size',
            field=models.IntegerField(blank=True, help_text='Mesh size of the net material in um', null=True, verbose_name='Mesh Size'),
        ),
        migrations.AlterField(
            model_name='discretesamplevalue',
            name='datatype',
            field=models.IntegerField(blank=True, null=True, verbose_name='BioChem DataType'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='data_center',
            field=models.IntegerField(default=20, verbose_name='Data Center'),
        ),
        migrations.AlterField(
            model_name='missionsampletype',
            name='datatype',
            field=models.IntegerField(blank=True, null=True, verbose_name='BioChem DataType'),
        ),
        migrations.AlterField(
            model_name='planktonsample',
            name='sex',
            field=models.IntegerField(default=90000000, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='planktonsample',
            name='stage',
            field=models.IntegerField(default=90000000, verbose_name='Stage of Life'),
        ),
        migrations.AlterField(
            model_name='planktonsample',
            name='taxa',
            field=models.IntegerField(verbose_name='Taxonomy'),
        ),
    ]
