# Generated by Django 4.2 on 2024-02-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('user_settings', '0002_fileconfiguration'), ('user_settings', '0003_fileconfiguration_description'), ('user_settings', '0004_globalgeographicregion_globalstation')]

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=20)),
                ('required_field', models.CharField(help_text='This is a field the parser will require to set DART table values', max_length=50, verbose_name='Required Field')),
                ('mapped_field', models.CharField(help_text='This is the field as it appears in the file being parsed', max_length=50, verbose_name='Mapped Field')),
                ('description', models.TextField(default='', help_text='Description of the purpose of the mapped field', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalGeographicRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Geographic Region Name')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Station Name')),
            ],
        ),
    ]
