# Generated by Django 4.2 on 2024-02-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0005_alter_fileconfiguration_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalstation',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='globalstation',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='globalstation',
            name='sounding',
            field=models.FloatField(blank=True, null=True, verbose_name='Sounding'),
        ),
        migrations.AlterField(
            model_name='globalgeographicregion',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Geographic Region Name'),
        ),
    ]
