# Generated by Django 4.2 on 2024-02-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0006_globalstation_latitude_globalstation_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalstation',
            name='fixstation',
            field=models.BooleanField(default=False, verbose_name='Fix Station'),
        ),
    ]
