# Generated by Django 4.2.23 on 2025-06-19 20:39

from django.db import migrations, models
import django.db.models.deletion


def migrate_user_settings_models(apps, schema_editor):
    settingsdb_models = apps.get_app_config('user_settings').get_models()
    user_settings_models = apps.get_app_config('user_settings').get_models()

    settingsdb_model_map = {model.__name__: model for model in settingsdb_models}
    user_settings_model_map = {model.__name__: model for model in user_settings_models}

    for model_name, settingsdb_model in settingsdb_model_map.items():
        if model_name in user_settings_model_map:
            user_settings_model = user_settings_model_map[model_name]
            for old_instance in settingsdb_model.objects.all():
                new_instance = user_settings_model()
                for field in settingsdb_model._meta.fields:
                    if hasattr(user_settings_model, field.name):
                        setattr(new_instance, field.name, getattr(old_instance, field.name))
                new_instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0010_globalsampletypecategory_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_user_settings_models),
        migrations.AlterField(
            model_name='globalsampletype',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Group sample types of similar type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_types', to='user_settings.globalsampletypecategory', verbose_name='Sample Type Category'),
        ),
        migrations.AlterField(
            model_name='sampletypeconfig',
            name='sample_type',
            field=models.ForeignKey(help_text='The sample type this config is intended for', on_delete=django.db.models.deletion.DO_NOTHING, related_name='configs', to='user_settings.globalsampletype', verbose_name='Sample Type'),
        ),
    ]
