# Generated by Django 4.2 on 2024-01-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_location', models.FilePathField(default='./missions', help_text='Location of individual mission databases', verbose_name='Mission Database(s) Path')),
            ],
        ),
    ]
