# Generated by Django 4.2 on 2024-02-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=20)),
                ('required_field', models.CharField(help_text='This is a field the parser will require to set DART table values', max_length=50, verbose_name='Required Field')),
                ('mapped_field', models.CharField(help_text='This is the field as it appears in the file being parsed', max_length=50, verbose_name='Mapped Field')),
            ],
        ),
    ]
