# Generated by Django 4.2 on 2024-02-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsdb', '0002_fileconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileconfiguration',
            name='description',
            field=models.TextField(default='', help_text='Description of the purpose of the mapped field', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
