# Generated by Django 4.2 on 2024-02-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsdb', '0003_globalsampletype_sampletypeconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcDatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.IntegerField(choices=[(1, 'Oracle')], default=1, verbose_name='Database Type')),
                ('host', models.CharField(max_length=50, verbose_name='Server Address')),
                ('name', models.CharField(help_text='TTRAN/PTRAN', max_length=20, verbose_name='Database Name')),
                ('port', models.IntegerField(default=1521, verbose_name='Port')),
                ('account_name', models.CharField(max_length=20, verbose_name='Account Name')),
                ('uploader', models.CharField(blank=True, help_text='If not Account Name', max_length=20, null=True, verbose_name='Uploader Name')),
            ],
        ),
    ]
