# Generated by Django 4.2 on 2024-02-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsdb', '0002_fileconfiguration_squashed_0004_globalgeographicregion_globalstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileconfiguration',
            name='description',
            field=models.TextField(help_text='Description of the purpose of the mapped field', verbose_name='Description'),
        ),
    ]
