# Generated by Django 4.2 on 2024-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsdb', '0007_globalstation_fixstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampletypeconfig',
            name='detection_limit_field',
            field=models.CharField(blank=True, help_text='Lowercase name of the column that contains flags, if it exists', max_length=50, null=True, verbose_name='Detection Limit Column'),
        ),
    ]
