# Generated by Django 4.2 on 2024-09-24 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingsdb', '0009_bcdatabaseconnection_bc_discrete_data_edits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSampleTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Sample Type Category')),
            ],
        ),
        migrations.AlterField(
            model_name='bcdatabaseconnection',
            name='bc_discrete_data_edits',
            field=models.CharField(default='BCDISCRETEDATAEDITS', help_text='BCD Data Table Name', max_length=60, verbose_name='BCD Discrete Table Name'),
        ),
        migrations.AlterField(
            model_name='bcdatabaseconnection',
            name='bc_discrete_station_edits',
            field=models.CharField(default='BCDISCRETESTATNEDITS', help_text='BCS Data Table Name', max_length=60, verbose_name='BCS Discrete Table Name'),
        ),
        migrations.AlterField(
            model_name='bcdatabaseconnection',
            name='bc_plankton_data_edits',
            field=models.CharField(default='BCPLANKTONDATAEDITS', help_text='BCD Plankton Table Name', max_length=60, verbose_name='BCD Plankton Table Name'),
        ),
        migrations.AlterField(
            model_name='bcdatabaseconnection',
            name='bc_plankton_station_edits',
            field=models.CharField(default='BCPLANKTONSTATNEDITS', help_text='BCS Plankton Table Name', max_length=60, verbose_name='BCS Plankton Table Name'),
        ),
        migrations.AddField(
            model_name='globalsampletype',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Group sample types of similar type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_types', to='settingsdb.globalsampletypecategory', verbose_name='Sample Type Category'),
        ),
    ]
