# Generated by Django 4.2 on 2025-10-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settingsdb', '0010_globalsampletypecategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bcdatabaseconnection',
            name='bc_discrete_data_edits',
        ),
        migrations.RemoveField(
            model_name='bcdatabaseconnection',
            name='bc_discrete_station_edits',
        ),
        migrations.RemoveField(
            model_name='bcdatabaseconnection',
            name='bc_plankton_data_edits',
        ),
        migrations.RemoveField(
            model_name='bcdatabaseconnection',
            name='bc_plankton_station_edits',
        ),
    ]
