# Generated by Django 4.2 on 2025-10-19 12:23

from django.db import migrations, models
import django.db.models.deletion


def consolidate_sample_type_configs(apps, schema_editor):
    SampleTypeConfig = apps.get_model('settingsdb', 'SampleTypeConfig')
    SampleTypeVariable = apps.get_model('settingsdb', 'SampleTypeVariable')
    SampleFileType = apps.get_model('settingsdb', 'SampleFileType')

    configs = SampleTypeConfig.objects.all()

    # Group configs by their common attributes
    grouped_configs = {}

    for config in configs:
        # Create a key based on the common fields
        key = (
            config.file_type,
            config.skip,
            config.sample_field,
            config.tab,
            config.allow_blank,
            config.allow_replicate
        )

        if key not in grouped_configs:
            grouped_configs[key] = []
        grouped_configs[key].append(config)

    keys = set(grouped_configs.keys())

    new_samplefiletypes = []
    for item, key in enumerate(keys):
        new_sft = SampleFileType(
            name=f"config_{item}",
            file_type=key[0].upper(),
            skip=int(key[1]),
            sample_field=key[2].upper(),
            tab=int(key[3]),
            comment_field="COMMENTS",
            are_blank_sample_ids_replicates=key[4],
            allowed_replicates=1 if key[5] else 0
        )
        new_samplefiletypes.append(new_sft)
    SampleFileType.objects.bulk_create(new_samplefiletypes)

    # Process each group
    for group in grouped_configs.values():
        if len(group) > 0:
            print(group[0])

            sample_file_type = SampleFileType.objects.get(
                file_type__iexact=group[0].file_type,
                skip=group[0].skip,
                tab=group[0].tab,
                sample_field__iexact=group[0].sample_field,
                are_blank_sample_ids_replicates=group[0].allow_blank,
            )

            # Keep the first config as primary
            primary_config = group[0]

            if "config_" in sample_file_type.name:
                sample_file_type.name = primary_config.sample_type.short_name
                sample_file_type.save()

            # Create a variable for the primary config first
            SampleTypeVariable.objects.create(
                sample_type=sample_file_type,
                name=primary_config.sample_type.short_name,
                value_field=primary_config.value_field.upper() if primary_config.value_field else None,
                flag_field=primary_config.flag_field.upper() if primary_config.flag_field else None,
                limit_field=primary_config.limit_field.upper() if primary_config.limit_field else None,
                datatype=primary_config.sample_type.datatype.pk
            )

            # Process duplicates if any
            if len(group) > 1:
                for duplicate in group[1:]:
                    # Create a variable for each duplicate
                    SampleTypeVariable.objects.create(
                        sample_type=sample_file_type,
                        name=duplicate.sample_type.short_name,
                        value_field=duplicate.value_field.upper() if duplicate.value_field else None,
                        flag_field=duplicate.flag_field.upper() if duplicate.flag_field else None,
                        limit_field=duplicate.limit_field.upper() if duplicate.limit_field else None,
                        datatype = duplicate.sample_type.datatype.pk
                    )


class Migration(migrations.Migration):

    dependencies = [
        ('settingsdb', '0010_globalsampletypecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short descriptive name for this configuration', max_length=100, verbose_name='Sample File Type')),
                ('file_type', models.CharField(help_text='The file extension in uppercase (CSV, XLS, DAT)', max_length=5, verbose_name='File Type')),
                ('skip', models.IntegerField(default=0, verbose_name='Header Row')),
                ('tab', models.IntegerField(default=0, verbose_name='Tab')),
                ('sample_field', models.CharField(help_text='Upper case name of the column that contains the value data', max_length=50, verbose_name='Sample Column')),
                ('comment_field', models.CharField(blank=True, help_text='Upper case name of the column containing comments, if it exists', max_length=50, null=True, verbose_name='Comment Column')),
                ('are_blank_sample_ids_replicates', models.BooleanField(default=True, verbose_name='Are Blank Sample IDs Replicates?')),
                ('allowed_replicates', models.IntegerField(default=1, help_text='The number of replicates allowed for this sample', verbose_name='Allowed Replicates?')),
            ],
        ),
        migrations.CreateModel(
            name='SampleTypeVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short descriptive name for this column of data', max_length=100, verbose_name='Sample File Type')),
                ('value_field', models.CharField(help_text='Lowercase name of the column that contains the value data', max_length=50, verbose_name='Value Column')),
                ('flag_field', models.CharField(blank=True, help_text='Lowercase name of the column that contains flags, if it exists', max_length=50, null=True, verbose_name='Flag Column')),
                ('limit_field', models.CharField(blank=True, help_text='Lowercase name of the column that contains flags, if it exists', max_length=50, null=True, verbose_name='Detection Limit Column')),
                ('datatype', models.IntegerField(blank=True, help_text='The biochem datatype this variable is intended for', null=True, verbose_name='Datatype')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='settingsdb.samplefiletype', verbose_name='Sample Type')),
            ],
        ),
        migrations.RunPython(
            consolidate_sample_type_configs,
            lambda apps, schema_editor: None
        )
    ]
