# Generated by Django 4.2 on 2026-01-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsdb', '0011_remove_bcdatabaseconnection_bc_discrete_data_edits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletypeconfig',
            name='allow_blank',
            field=models.BooleanField(default=True, help_text='If the sample id column for the row is empty, should the value be considered a replicate?', verbose_name='Allow Blank Samples?'),
        ),
    ]
