# Generated by Django 5.2.9 on 2026-01-21 20:02

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsdb', '0012_alter_sampletypeconfig_allow_blank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsampletype',
            options={'ordering': ('is_sensor', django.db.models.functions.text.Lower('short_name'))},
        ),
        migrations.AlterField(
            model_name='globalsampletype',
            name='short_name',
            field=models.CharField(help_text='The column name of a sensor or a short name commonly used for the sample', max_length=20, verbose_name='Short/Column Name'),
        ),
    ]
