# Generated by Django 5.2.13 on 2026-04-11 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsdb', '0013_alter_globalsampletype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleFileConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('file_type', models.CharField(help_text='file type extension e.g csv, xls, xlsx, dat', max_length=5, verbose_name='File Type')),
                ('tab', models.IntegerField(default=0, help_text='The tab number in the file', verbose_name='Tab')),
                ('header_line', models.IntegerField(default=0, verbose_name='Header Row')),
                ('sample_id_column_name', models.CharField(max_length=20, verbose_name='Sample ID Column Name')),
                ('comment_column_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Comment Column Name')),
            ],
        ),
        migrations.CreateModel(
            name='SampleFileConfigColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_alias', models.CharField(max_length=20, verbose_name='Alias Column')),
                ('value_column_name', models.CharField(max_length=50, verbose_name='Value Column Name')),
                ('detection_limit_column_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Detection Limit Column Name')),
                ('quality_control_column_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quality Control Column Name')),
                ('datatype_id', models.IntegerField(blank=True, null=True, verbose_name='Datatype ID Column Name')),
                ('file_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_columns', to='settingsdb.samplefileconfig', verbose_name='File Config Columns')),
            ],
        ),
    ]
