# Generated by Django 5.2.14 on 2026-06-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsdb', '0014_samplefileconfig_samplefileconfigcolumns'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplefileconfig',
            name='allow_blank_sample_ids',
            field=models.BooleanField(default=True, help_text='If false, values on lines that do not have sample IDs will be ignored', verbose_name='Allow blank sample IDs?'),
        ),
        migrations.AddField(
            model_name='samplefileconfig',
            name='allow_replicates',
            field=models.BooleanField(default=True, help_text='If false, warnings will be created if Sample IDs appear more than once', verbose_name='Allow Replicates?'),
        ),
    ]
